//Auth
export const SET_TOKENS = "SET_TOKENS";
export const SET_REFRESH_RESULT = "SET_REFRESH_RESULT";
export const SET_LOGGED_USER = "SET_LOGGED_USER";


export const LOGOUT = "LOGOUT";

//Register
export const SET_REGISTER_NAME = 'SET_REGISTER_NAME';

//Home
export const SET_EXAMS_LIST_LIVE = 'SET_EXAMS_LIST_LIVE';
export const SET_EXAMS_LIST_PRACTICE = 'SET_EXAMS_LIST_PRACTICE';
export const SET_COURSESS_LIST = 'SET_COURSESS_LIST';

//Exam
export const SET_EXAM_LIST = 'SET_EXAM_LIST';
export const SET_EXAM_FULL_LIST = 'SET_EXAM_FULL_LIST';
export const SET_EXAM_DETAILS = 'SET_EXAM_DETAILS';
export const SET_TAKE_EXAM_DETAILS = 'SET_TAKE_EXAM_DETAILS';
export const SET_EXAM_RESULT = 'SET_EXAM_RESULT';
export const SUBMIT_EXAM = 'SUBMIT_EXAM';
export const SET_SUBMITTING = "SET_SUBMITTING";
export const SET_SHOW_SUBMITTING = "SET_SHOW_SUBMITTING";

//Reset Password
export const SET_COUNTER = "SET_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";


//Loading
export const SET_LOADING = 'SET_LOADING';

//Popup
export const SET_SUCCESS_POPUP = 'SET_SUCCESS_POPUP';

//Course
export const SET_COURSE_LIST = 'SET_COURSE_LIST';
export const SET_COURSE_DETAILS = "SET_COURSE-DETAILS";
export const SET_MY_COURSES = "SET_MY_COURSES";
export const SET_MY_COURSE_DETAIL = "SET_MY_COURSE_DETAIL";
export const SET_COURSE_EXAMS = "SET_COURSE_EXAMS";

